import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import NavigationBar from "./components/Navigationbar/Navigationbar";
import Cursor from "./components/Cursor/Cursor";

const geistSans = localFont({
       src: "./fonts/GeistVF.woff",
       variable: "--font-geist-sans",
       weight: "100 900",
});
const geistMono = localFont({
       src: "./fonts/GeistMonoVF.woff",
       variable: "--font-geist-mono",
       weight: "100 900",
});

export const metadata: Metadata = {
       title: "Orange Egypt",
       description: "Generated by create next app",
};

export default function RootLayout({
       children,
}: Readonly<{
       children: React.ReactNode;
}>) {
  return (
       <html lang="ar">
       <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
       >
              <NavigationBar />
              {children}

              {/* <Cursor/> */}
       </body>
       </html>
       );
}
